### ISSUE TITLE
Question regarding littleFS

### ISSUE THREAD

**Issue by hasenradball** [earlephilhower/arduino-pico-littlefs-plugin#12]
@earlephilhower 
when using / needed a filesysten would you usecthe arduino framework for the pi pico or the c sdk of the Pico?

Best regards 
Frank

**Comment by earlephilhower** [comment]
Unless something has changed that I'm not aware of, the SDK has no filesystem support.  You can definitely roll your own LittleFS implementation, they make it relatively easy to do.  You'd be calling the `lfs_XXX` calls natively, not `fopen()` or whatever, but there's almost a 1:1 mapping.

This plugin is only useful for the Arduino Core, of course, since it depends on the memory and linker files present on the Pico _[edit, this is the 1.0 plugin only for Pico]_ ~~(and ESP32 and ESP8266)~~.  `mklittlefs`, the app which makes the filesystem bitstream for upload, can be used for roll-your-own LittleFS as long as you set the parameters appropriately and run it manually.  Uploading to the Pico after doing so it a problem left for the student. :laughing:

**Comment by hasenradball** [comment]
Thanks for your answer.
I am comming from the Esp family with the arduino core.
As I started with the pico, first started with micropython but from the bottom of my heart I like c/ cpp.

But it seems easier to stick on the arduino core than using the c sdk for the pico.
